Repository rancher/aks-operator, pull requests merged in 2024-10, with the labels that each got.

#675 [v1.31] Bump k8s dependencies to support k8s v1.31
  go.mod
  go.sum
Labels: kind/enhancement

#685 [v2.7] Bump image version
  .github/workflows/release.yaml
  .github/workflows/scan.yaml
  .trivyignore
  package/Dockerfile
Labels: area/release, area/ci

#692 ci: Use Go 1.23
  .github/workflows/release.yaml
  .github/workflows/scan.yaml
  .trivyignore
Labels: area/ci
